/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parser@7.28.6_@floating-ui+dom@1.7.4_@inertiajs+vue3@2.3.11_vue@3_16a00937ec306709b8e5b2dc547f46f3/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.3.0_@babel+parser@7.28.6_@floating-ui+dom@1.7.4_@inertiajs+vue3@2.3.11_vue@3_16a00937ec306709b8e5b2dc547f46f3/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
  }
}
